apiVersion: v1
kind: ConfigMap
metadata:
  name: cryptpad-config
  namespace: communishift-draft-share
  labels:
    app: cryptpad
data:
  config.js: |
    // Generated config -- see https://docs.cryptpad.org/en/admin_guide/installation.html#configure-cryptpad
    module.exports = {
      httpUnsafeOrigin: 'https://cryptpad-communishift-draft-share.apps.fedora.cj14.p1.openshiftapps.com',
      httpSafeOrigin: 'https://cryptpad-sandbox-communishift-draft-share.apps.fedora.cj14.p1.openshiftapps.com',
      httpAddress: '0.0.0.0',
      httpPort: 3000,
      websocketPath: undefined,
      adminKeys: [
        "[admin-poc@cryptpad-communishift-draft-share.apps.fedora.cj14.p1.openshiftapps.com/MxQshfwmY6Ag3MTv4Al+iACeEomGLy4x1iyybK+VqAk=]"
      ],
      installMethod: 'docker',
    };
