apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: cryptpad-storage
  namespace: communishift-draft-share
  labels:
    app: cryptpad
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi
